name: Slither Analysis

on:
  push:
    branches: [ development ]
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/setup-node@v13
        with:
          node-version: '14'
      - uses: actions/setup-python@v2
        with:
         python-version: '3.8'
    - name: Prepare environment
      run: |
        npm install -g ganache-cli@6.12.1
        pip3 install solc-select
        solc-select install 0.8.4
        solc-select use 0.8.4
        pip3 install slither-analyzer
        pip install -r requirements-dev.txt
    - name: Run Slither
      uses: crytic/slither-action@v0.1.1
      continue-on-error: true
      id: slither