name: Security-checks

on:
  push:
    branches: [ development ]
  pull_request:

jobs:
  main_job:
    runs-on: ubuntu-latest
    name: Solidity Security
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/setup-python@v2
        with:
         python-version: '3.8'
      - name: Prepare environment
        run: |
         npm install -g ganache-cli@6.12.1
         pip3 install solc-select
         solc-select install 0.8.3
         solc-select use 0.8.3
         pip3 install slither-analyzer
         pip install -r requirements-dev.txt
      - name: Slither Static Analysis
        uses: crytic/slither-action@v0.1.1
        continue-on-error: true
        id: slither
        with:
          sarif: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
